config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :users
  resources :posts do
    member do
      post 'like'
      post 'dislike'
    end
    resources :comments do
      member do
        post 'like'
        post 'dislike'
      end
    end
  end
  root to: "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :posts, except: [:new, :edit]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :reactions, as: :likeable
  belongs_to :user


  validates :body, presence: true
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApiController
      skip_before_action :verify_authenticity_token, only: [:destroy, :create, :update]

      def index
        @posts = Post.all
        serialized_posts = PostSerializer.new(@posts).serializable_hash # Serialize to hash
        render json: serialized_posts.to_json
      end

      def create
        @post = Post.new(post_params)
        if @post.save
          serialized_post = PostSerializer.new(@post).serializable_hash
          render json: { message: 'Post created successfully', post: serialized_post }, status: :created
        else
          render json: { message: 'Failed to create post', errors: @post.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def show
        @post = Post.find(params[:id])
        serialized_post = PostSerializer.new(@post).serializable_hash
        render json: serialized_post.to_json
      end

      def destroy
        @post = Post.find_by(id: params[:id])
        if !@post.nil? && @post.destroy
          serialized_post = PostSerializer.new(@post).serializable_hash
          render json: { message: 'Post deleted successfully', post: serialized_post }, status: :ok
        else
          render json: { message: 'Failed to delete post' }, status: :unprocessable_entity
        end
      end

      def update
        @post = Post.find_by(id: params[:id])
        if !@post.nil? && @post.update(post_params)
          render json: { message: 'Post updated successfully' }, status: :ok
        else
          render json: { message: 'Failed to delete post' }, status: :unprocessable_entity
        end
      end

      private

      def post_params
        params.require(:post).permit(:title, :body, :user_id)
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy like dislike ]

  def index
    @posts = Post.includes(:reactions).all
  end

  def show
    @posted_comments=@post.comments.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: t('notice') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.nil? || @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: t('notice') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @post.nil? || @post.destroy
        format.html { redirect_to posts_url, notice: t('notice') }
      else
        format.html { redirect_to posts_url, status: :unprocessable_entity }
      end
    end
  end

  def like
    toogle_reaction(true)
    redirect_to posts_url
  end

  def dislike
    toogle_reaction(false)
    redirect_to posts_url
  end

  private

    def toogle_reaction(reaction_type)
      existing_reaction = Reaction.find_by(user_id: current_user.id, likeable_id: @post.id, likeable_type: "Post")
      if existing_reaction && existing_reaction.like == reaction_type
        existing_reaction.destroy
      elsif existing_reaction==nil
        @post.reactions.create(user_id: current_user.id, like: reaction_type)
      else
        @post.reactions.update(like: reaction_type)
      end
    end

    def set_post
      @post = Post.find_by(id: params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/views/posts/_comment.html.erb
<tr>
    <td><%= comment.content %></td>
    <td><%= comment.user.email %></td>
    <td><%= link_to 'Destroy', post_comment_path(post_id, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<tr>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "post", collection: @posts %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>




<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Posted by</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: "comment", collection: @posted_comments , locals: { post_id: @post.id } %>
  </tbody>
</table>



<%= form_with(model: [@post, @post.comments.build], url: post_comments_path(@post)) do |form| %>
  <%= form.text_area :content, placeholder: 'Enter your comment' %>
  <%= form.submit 'Add Comment' %>
<% end %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>